name: Compile

on:
  push:
    branches: [ "master", "workflow" ]
  pull_request:
    branches: [ "master", "workflow" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4.0.3
      with: 
        node-version: 18

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 7
        run_install: false

    - name: Install dependencies
      run: pnpm install --ignore-scripts --ignore-optional
        
    - name: compile
      run: pnpm run build
        
