name: Compile

on:
  push:
    branches: [ "master", "workflow" ]
  pull_request:
    branches: [ "master", "workflow" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4.0.3
      with: 
        node-version: 20

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.3.0
        run_install: false

    - name: Install dependencies of pnpm
      run: pnpm install --frozen-lockfile
        
    - name: compile
      run: pnpm run tauri-build
      
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: src-tauri/target/release/bundle/nsis/层合板力学性能计算程序_4.0.0_x64-setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
