name: Compile

on:
  push:
    branches: [ "master", "workflow" ]
  pull_request:
    branches: [ "master", "workflow" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4.0.3
      with: 
        node-version: 20

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: install dependencies of ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 8.9.0
        run_install: false

    - name: Install dependencies of pnpm
      run: pnpm install --frozen-lockfile
        
    - name: compile
      run: pnpm run tauri-build

